"""Versioned artifact contracts shared by VNTTS producers and consumers."""

__version__ = "0.7.2"

from vntts_artifacts.audio import PCM16_MONO_WAV_FORMAT
from vntts_artifacts.game_pack import (
    GAME_PACK_SCHEMA,
    GAME_PACK_SCHEMA_VERSION,
    GamePack,
    GamePackArtifactBinding,
    GamePackError,
    GamePackProducer,
    create_game_pack_artifact_bindings,
    load_game_pack,
    validate_game_pack_artifact_bindings,
    write_game_pack,
)
from vntts_artifacts.generated_audio import (
    GENERATED_AUDIO_SCHEMA,
    GENERATED_AUDIO_SCHEMA_VERSION,
    GeneratedAudioDocument,
    GeneratedAudioEntry,
    GeneratedAudioIndex,
    GeneratedAudioManifestError,
    GeneratedAudioRecord,
    load_generated_audio_document,
    load_generated_audio_manifest,
    write_generated_audio_document,
    write_generated_audio_manifest,
)
from vntts_artifacts.hashing import text_sha256
from vntts_artifacts.live_sequence import (
    LIVE_SEQUENCE_SCHEMA,
    LIVE_SEQUENCE_SCHEMA_VERSION,
    LiveSequenceChapter,
    LiveSequenceEvent,
    LiveSequencePlan,
    LiveSequencePlanError,
    load_live_sequence_plan,
    write_live_sequence_plan,
)
from vntts_artifacts.story_index import (
    SOURCE_AUDIO_STATUSES,
    STORY_INDEX_SCHEMA,
    STORY_INDEX_SCHEMA_VERSION,
    StoryIndexCollection,
    StoryIndexDocument,
    StoryIndexError,
    StoryIndexLine,
    StoryIndexRecord,
    load_story_index,
    load_story_index_document,
    write_story_index,
    write_story_index_document,
)
from vntts_artifacts.voice_generation_queue import (
    CANONICAL_VOICE_GENERATION_ACTION_BY_SOURCE_AUDIO_STATUS,
    VOICE_GENERATION_ACTION_BY_SOURCE_AUDIO_STATUS,
    VOICE_GENERATION_ACTIONS,
    VOICE_GENERATION_EXCLUDED_SOURCE_AUDIO_STATUSES,
    VOICE_GENERATION_QUEUE_SCHEMA,
    VOICE_GENERATION_QUEUE_SCHEMA_VERSION,
    VOICE_GENERATION_UNKNOWN_SOURCE_AUDIO_ACTIONS,
    VoiceGenerationQueue,
    VoiceGenerationQueueError,
    VoiceGenerationQueueItem,
    expected_voice_generation_queue_id,
    load_voice_generation_queue,
    voice_generation_action,
    write_voice_generation_queue,
)
from vntts_artifacts.voice_manifest import VOICE_MANIFEST_VERSION

__all__ = [
    "__version__",
    "CANONICAL_VOICE_GENERATION_ACTION_BY_SOURCE_AUDIO_STATUS",
    "GENERATED_AUDIO_SCHEMA",
    "GENERATED_AUDIO_SCHEMA_VERSION",
    "GAME_PACK_SCHEMA",
    "GAME_PACK_SCHEMA_VERSION",
    "GamePack",
    "GamePackArtifactBinding",
    "GamePackError",
    "GamePackProducer",
    "LIVE_SEQUENCE_SCHEMA",
    "LIVE_SEQUENCE_SCHEMA_VERSION",
    "LiveSequenceChapter",
    "LiveSequenceEvent",
    "LiveSequencePlan",
    "LiveSequencePlanError",
    "GeneratedAudioDocument",
    "GeneratedAudioEntry",
    "GeneratedAudioIndex",
    "GeneratedAudioManifestError",
    "GeneratedAudioRecord",
    "PCM16_MONO_WAV_FORMAT",
    "SOURCE_AUDIO_STATUSES",
    "STORY_INDEX_SCHEMA",
    "STORY_INDEX_SCHEMA_VERSION",
    "StoryIndexCollection",
    "StoryIndexDocument",
    "StoryIndexError",
    "StoryIndexLine",
    "StoryIndexRecord",
    "VOICE_MANIFEST_VERSION",
    "VOICE_GENERATION_ACTION_BY_SOURCE_AUDIO_STATUS",
    "VOICE_GENERATION_ACTIONS",
    "VOICE_GENERATION_EXCLUDED_SOURCE_AUDIO_STATUSES",
    "VOICE_GENERATION_QUEUE_SCHEMA",
    "VOICE_GENERATION_QUEUE_SCHEMA_VERSION",
    "VOICE_GENERATION_UNKNOWN_SOURCE_AUDIO_ACTIONS",
    "VoiceGenerationQueue",
    "VoiceGenerationQueueError",
    "VoiceGenerationQueueItem",
    "create_game_pack_artifact_bindings",
    "load_game_pack",
    "load_live_sequence_plan",
    "load_generated_audio_document",
    "load_generated_audio_manifest",
    "load_story_index",
    "load_story_index_document",
    "load_voice_generation_queue",
    "expected_voice_generation_queue_id",
    "text_sha256",
    "validate_game_pack_artifact_bindings",
    "voice_generation_action",
    "write_voice_generation_queue",
    "write_generated_audio_document",
    "write_generated_audio_manifest",
    "write_game_pack",
    "write_live_sequence_plan",
    "write_story_index",
    "write_story_index_document",
]
